schema_version = "1.0.0"

id = "autosculptor"
version = "1.8.0"
name = "Autosculptor"
tagline = "Generate 3D models using generative models."
maintainer = "gsbm"
type = "add-on"

permissions = ["files", "network"]
website = "https://github.com/gsbm/autosculptor"
tags = ["Add Mesh", "AI", "Mesh", "Generation", "Text"]
blender_version_min = "2.8.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
